import type { Metadata } from "next";
import { Poppins, Six_Caps } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const poppins = Poppins({
  weight: ["400"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const sixCaps = Six_Caps({
  weight: ["400"],
  variable: "--font-six-caps",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Montoya project animation",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${sixCaps.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
